repos:
  - repo: https://github.com/omnilib/ufmt
    rev: v2.7.0
    hooks:
    -   id: ufmt
        additional_dependencies:
        -   ruff-api==0.1.0
        -   black==25.1.0
        -   usort==1.0.8.post1
  - repo: local
    hooks:
      - id: check-license-headers
        name: Check license headers
        entry: python .github/scripts/check_license_headers.py
        language: system
        files: \.py$
        pass_filenames: true