# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD 3-Clause license found in the
# LICENSE file in the root directory of this source tree.

import logging
import os
from typing import Callable, Dict

from BackendBench.utils import (
    compile_kernel_from_string,
    extract_operator_name,
    op_name_to_folder_name,
)

from .base import Backend

logger = logging.getLogger(__name__)


class KernelAgentBackend(Backend):
    """
    Backend that uses KernelAgent for sophisticated parallel kernel generation.

    This backend leverages KernelAgent's advanced features:
    - Parallel workers with iterative refinement
    - Multi-turn conversation history
    - Comprehensive prompt engineering with Triton guidelines
    - Automatic test generation
    """

    def __init__(self) -> None:
        super().__init__("kernel_agent")
        self.compiled_kernels: Dict[str, Callable] = {}

        # Create generated_kernels directory
        import datetime

        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        self.kernels_dir = f"generated_kernels/kernel_agent_run_{timestamp}"
        os.makedirs(self.kernels_dir, exist_ok=True)

        # Create README for this run
        readme_path = os.path.join(self.kernels_dir, "README.md")
        with open(readme_path, "w") as f:
            f.write(
                f"""# Generated Kernels - KernelAgent - {timestamp}

This directory contains PyTorch/Triton kernels generated by the KernelAgent Backend.

## Run Info
- Timestamp: {timestamp}
- Backend: KernelAgent
- Features: Parallel workers, iterative refinement, conversation history

## Files
Each `<op_name>_kernel.py` file contains the complete generated kernel code for that operation.
KernelAgent session directories contain detailed logs, worker outputs, and generation artifacts.

## KernelAgent Features Used
- Parallel workers for increased success rate
- Iterative refinement with multi-turn dialogue
- Comprehensive Triton programming guidelines
- Automatic test generation and validation
- Session logging and artifact preservation

## Usage
You can inspect these files to debug kernel generation, analyze the parallel worker outputs,
or understand the sophisticated generation process used by KernelAgent.
"""
            )

        print(f"Saving KernelAgent generated kernels to: {self.kernels_dir}")

        self.kernel_agent = None
        self.num_workers = 4
        self.max_rounds = 10

    def set_config(self, num_workers: int, max_rounds: int):
        """Set configuration for KernelAgent."""
        self.num_workers = num_workers
        self.max_rounds = max_rounds

    def _get_kernel_agent(self):
        """Lazy initialization of KernelAgent to avoid import issues."""
        if self.kernel_agent is None:
            try:
                from triton_kernel_agent import TritonKernelAgent

                agent_log_dir = os.path.join(self.kernels_dir, "agent_logs")
                os.makedirs(agent_log_dir, exist_ok=True)

                self.kernel_agent = TritonKernelAgent(
                    log_dir=agent_log_dir,
                    num_workers=self.num_workers,
                    max_rounds=self.max_rounds,
                )

                print(f"✓ KernelAgent initialized with log directory: {agent_log_dir}")

            except ImportError:
                raise ImportError(
                    "triton_kernel_agent package not found. Install it to use KernelAgent backend."
                )

        return self.kernel_agent

    def _create_problem_description_from_op(self, op, op_name: str) -> str:
        """
        Create a problem description for KernelAgent based on the PyTorch operation.

        Args:
            op: PyTorch operation
            op_name: Operation name extracted from op

        Returns:
            Problem description string for KernelAgent
        """
        # Create a comprehensive problem description that KernelAgent can understand
        problem_description = f"""
Implement a high-performance Triton kernel for the PyTorch operation: {op_name}

Operation details:
- PyTorch operation: {op}
- Operation name: {op_name}
- Framework target: OpenAI Triton

Requirements:
1. The kernel must be functionally equivalent to the PyTorch operation
2. Implement using Triton language primitives (tl.load, tl.store, etc.)
3. Handle all tensor shapes and data types that the original operation supports
4. Optimize for GPU performance with proper memory coalescing
5. Include proper boundary condition handling
6. Follow Triton best practices for kernel design

The generated kernel should:
- Take the same input arguments as the PyTorch operation
- Return outputs with identical shapes, dtypes, and numerical values
- Be optimized for common tensor shapes and memory layouts
- Handle edge cases gracefully

Please generate a complete, production-ready Triton kernel implementation.
"""
        return problem_description

    def _adapt_kernel_function_name(self, kernel_code: str, op_name: str) -> str:
        """
        Adapt KernelAgent's 'kernel_function' to BackendBench's expected naming convention.

        KernelAgent generates kernels with 'kernel_function' as the main entry point.
        BackendBench expects '{op_name}_kernel_impl' as the function name.

        Args:
            kernel_code: Original kernel code from KernelAgent
            op_name: Operation name for the expected function name

        Returns:
            Modified kernel code with correct function name
        """
        folder_name = op_name_to_folder_name(op_name)
        expected_name = f"{folder_name}_kernel_impl"

        # Replace 'def kernel_function' with 'def {op_name}_kernel_impl'
        if "def kernel_function(" in kernel_code:
            adapted_code = kernel_code.replace("def kernel_function(", f"def {expected_name}(")

            # Also replace any docstring references
            adapted_code = adapted_code.replace(
                '"""Wrapper function that handles kernel launch."""',
                f'"""{op_name} kernel implementation using Triton."""',
            )

            return adapted_code
        else:
            # If kernel_function is not found, add a wrapper that calls the existing function
            wrapper_code = f'''

def {expected_name}(*args, **kwargs):
    """{op_name} kernel implementation using Triton - BackendBench adapter."""
    # Call the original kernel_function from KernelAgent
    return kernel_function(*args, **kwargs)
'''
            return kernel_code + wrapper_code

    def _generate_kernel_file_path(self, folder_name: str, attempt: int) -> str:
        """Generate the file path for a kernel, creating the operator subdirectory if needed."""
        op_dir = os.path.join(self.kernels_dir, folder_name)
        os.makedirs(op_dir, exist_ok=True)
        return os.path.join(op_dir, f"{folder_name}_implementation_v{attempt}.py")

    def compile_kernel_from_string(
        self, kernel_code: str, op_name: str, attempt: int = 1
    ) -> Callable:
        """Compile a kernel from string code and return a callable."""
        folder_name = op_name_to_folder_name(op_name)
        adapted_code = self._adapt_kernel_function_name(kernel_code, op_name)
        kernel_file_path = self._generate_kernel_file_path(folder_name, attempt)
        module_name = f"{folder_name}_implementation_v{attempt}"
        kernel = None
        try:
            kernel = compile_kernel_from_string(
                kernel_code=adapted_code,
                op_name=op_name,
                kernel_file_path=kernel_file_path,
                expected_fn_name=folder_name,
                module_name=module_name,
            )
        except Exception as e:
            raise e
        return kernel

    def add_kernel(self, op, kernel_code: str, op_name: str, attempt: int = 1):
        """Add a kernel implementation for a specific operator."""
        try:
            compiled_kernel = self.compile_kernel_from_string(kernel_code, op_name, attempt=attempt)
            self.compiled_kernels[op] = compiled_kernel
        except Exception as e:
            print(f"❌ Failed to compile kernel for {op_name}: {e}")

    def generate_kernel_with_agent(self, op, op_name: str) -> tuple[str, bool]:
        """
        Generate a kernel using KernelAgent's sophisticated generation system.

        Args:
            op: PyTorch operation
            op_name: Operation name

        Returns:
            tuple: (kernel_code, success)
        """
        try:
            agent = self._get_kernel_agent()

            # Create problem description
            problem_description = self._create_problem_description_from_op(op, op_name)

            print(
                f"🚀 Generating {op_name} kernel with KernelAgent (parallel workers + refinement)"
            )

            # Generate kernel using KernelAgent
            result = agent.generate_kernel(
                problem_description=problem_description,
                test_code=None,  # Let KernelAgent auto-generate the test
            )

            if result["success"]:
                print(f"✅ KernelAgent succeeded for {op_name}!")
                print(
                    f"   Worker {result['worker_id']} found solution in {result['rounds']} rounds"
                )
                print(f"   Session: {result['session_dir']}")

                # Copy the session directory to our kernels directory for preservation
                import shutil

                session_name = os.path.basename(result["session_dir"])
                folder_name = op_name_to_folder_name(op_name)
                preserved_session = os.path.join(
                    self.kernels_dir, f"{folder_name}_session_{session_name}"
                )
                try:
                    shutil.copytree(result["session_dir"], preserved_session)
                    print(f"   Session preserved: {preserved_session}")
                except Exception as e:
                    print(f"   Warning: Could not preserve session: {e}")

                return result["kernel_code"], result["rounds"], True
            else:
                print(f"❌ KernelAgent failed for {op_name}: {result['message']}")
                return "", result["rounds"], False

        except Exception as e:
            print(f"❌ KernelAgent error for {op_name}: {e}")
            return "", 0, False

    def generate_kernels(self, suite, daemon=True):
        """Generate kernels for all operators in the suite with comprehensive feedback."""
        self.daemon = daemon
        successful_ops = 0
        total_ops = 0

        for op_test in suite:
            total_ops += 1
            op = op_test.op
            op_str = str(op)
            op_name = extract_operator_name(op_str)
            folder_name = op_name_to_folder_name(op_name)

            logger.info(f"Generating kernel for {op_name} (full op: {op_str})")

            # Generate kernel with feedback-driven retry
            kernel_code, best_kernel_attempt, success = self.generate_kernel_with_agent(
                op=op, op_name=op_name
            )

            # Add kernel to backend and track success
            self.add_kernel(op, kernel_code, op_name)
            if success:
                successful_ops += 1
                logger.info(f"✓ Success! Best attempt: {best_kernel_attempt}")
            else:
                logger.info(f"✗ Failed after {best_kernel_attempt} rounds")

            # Write operation summary in the operator subdirectory
            self._write_summary(
                folder_name=folder_name,
                op_name=op_name,
                op_str=op_str,
                best_kernel_attempt=best_kernel_attempt,
                success=success,
            )

        # Generate and save overall summary
        self._write_overall_summary(successful_ops, total_ops)

    def _write_summary(
        self,
        folder_name: str,
        op_name: str,
        op_str: str,
        best_kernel_attempt: int,
        success: bool,
    ):
        """Write operation summary to the operator subdirectory."""
        op_dir = os.path.join(self.kernels_dir, folder_name)
        os.makedirs(op_dir, exist_ok=True)
        summary_file = os.path.join(op_dir, f"{folder_name}_summary.txt")
        with open(summary_file, "w") as f:
            f.write(f"Operation: {op_name}\n")
            f.write(f"Full op: {op_str}\n")
            f.write("Backend: KernelAgent\n")
            f.write(f"Workers: {self.num_workers}\n")
            f.write(f"Max rounds: {self.max_rounds}\n")
            f.write(f"Best kernel attempt: {best_kernel_attempt}\n")
            f.write(f"Final Status: {'✓ Success' if success else '✗ Failure'}\n")
            f.write(f"Final kernel file: {folder_name}_implementation_v{best_kernel_attempt}.py\n")

    def _write_overall_summary(self, successful_ops: int, total_ops: int):
        """Write overall summary of kernel generation results."""
        failed_ops = total_ops - successful_ops
        success_rate = f"{successful_ops / total_ops * 100:.1f}%" if total_ops > 0 else "0.0%"

        summary_lines = [
            "=" * 60,
            "KERNEL AGENT BACKEND SETUP SUMMARY",
            "=" * 60,
            f"Total operations attempted: {total_ops}",
            f"Successfully created correct kernels for: {successful_ops} ops",
            f"Failed to create correct kernels for: {failed_ops} ops",
            f"Success rate: {success_rate}",
            f"Workers: {self.num_workers}",
            f"Max rounds: {self.max_rounds}",
            f"Generated kernels saved to: {self.kernels_dir}",
            "Backend: KernelAgent",
            "=" * 60,
        ]

        # Log summary
        for line in summary_lines:
            logger.info(line)

        # Save to file
        with open(os.path.join(self.kernels_dir, "OVERALL_SUMMARY.txt"), "w") as f:
            f.write("\n".join(summary_lines))

    def __getitem__(self, key):
        if key in self.compiled_kernels:
            return self.compiled_kernels[key]
        raise KeyError(f"No KernelAgent kernel implementation found for {key}")

    def __contains__(self, key):
        return key in self.compiled_kernels
