name: Lint and Format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      
    - name: Set up Python
      run: uv python install
    
    - name: Install package with dev dependencies
      run: uv sync --dev
    
    - name: Run ufmt check
      run: uv run ufmt check .
    
    - name: Check license headers
      run: python .github/scripts/check_license_headers.py $(find . -name "*.py" -type f -not -path "./.venv/*" -not -path "./__pycache__/*") 