name: Ruff

on:
  push:
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install ruff
      run: pip install ruff==0.12.1
    
    - name: Run ruff check
      run: ruff check .
    
    - name: Run ruff format check
      run: ruff format --check . 