name: Ruff

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install package with dev dependencies
      run: pip install -e .[dev]
    
    - name: Run ruff check
      run: ruff check .
    
    - name: Run ruff format check
      run: ruff format --check . 